name: release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout project directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get previous tag
        id: tag
        uses: WyriHaximus/github-action-get-previous-tag@v1
        with:
          fallback: '0.0.0'

      - name: Get version
        id: version
        uses: WyriHaximus/github-action-next-semvers@v1
        with:
          version: ${{ steps.tag.outputs.tag }}

      - name: Select version
        id: select_version
        run: |
          if [ "${{ github.event.inputs.release_type }}" = "major" ]; then
            echo "version=${{ steps.version.outputs.major }}" >> $GITHUB_OUTPUT
            echo "full_version=${{ steps.version.outputs.v_major }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.release_type }}" = "minor" ]; then
            echo "version=${{ steps.version.outputs.minor }}" >> $GITHUB_OUTPUT
            echo "full_version=${{ steps.version.outputs.v_minor }}" >> $GITHUB_OUTPUT
          elif [ "${{ github.event.inputs.release_type }}" = "patch" ]; then
            echo "version=${{ steps.version.outputs.patch }}" >> $GITHUB_OUTPUT
            echo "full_version=${{ steps.version.outputs.v_patch }}" >> $GITHUB_OUTPUT
          fi

      - name: Setup java-maven
        uses: quiz-me-up/reusable-workflow/.github/actions/setup-java-maven@master

      - name: Update pom.xml versions
        run: mvn versions:set -DnewVersion=${{ steps.select_version.outputs.version }} -DprocessAllModules=true -DgenerateBackupPoms=false

      - name: Create Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --allow-empty -m "ci: bump version to ${{ steps.select_version.outputs.full_version }}"
          git tag -a ${{ steps.select_version.outputs.full_version }} -m "ci: bump version to ${{ steps.select_version.outputs.full_version }}"
          git push origin master --follow-tags

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.select_version.outputs.full_version }}
          release_name: Release ${{ steps.select_version.outputs.full_version }}

      - name: Deploy to github packages
        shell: bash
        run: mvn -Dmaven.test.skip deploy
