name: release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type (major, minor, patch)'
        required: true
        default: 'patch'
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout project directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Generate next version
        id: next_version
        uses: quiz-me-up/reusable-workflow/.github/actions/next-version@master
        with:
          release_type: ${{ github.event.inputs.release_type }}
          fallback_version: '0.0.0'

      - name: Setup java-maven
        uses: quiz-me-up/reusable-workflow/.github/actions/setup-java-maven@master

      - name: Update pom.xml versions
        run: mvn versions:set -DnewVersion=${{ steps.next_version.outputs.version }} -DprocessAllModules=true -DgenerateBackupPoms=false

      - name: Create Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --allow-empty -m "release ${{ steps.next_version.outputs.full_version }}"
          git tag -a ${{ steps.next_version.outputs.full_version }} -m "release ${{ steps.next_version.outputs.full_version }}"
          git push origin master --follow-tags

      - name: Create release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.next_version.outputs.full_version }}
          release_name: Release ${{ steps.next_version.outputs.full_version }}

      - name: Deploy to github packages
        run: mvn -Dmaven.test.skip deploy
