name: tag

on:
  workflow_run:
    workflows: ["build"]
    branches: [master]
    types:
      - completed

jobs:
  tag:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Checkout project directory
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # required for github-action-get-previous-tag

      - name: Get previous tag
        id: tag
        uses: 'WyriHaximus/github-action-get-previous-tag@v1'
        with:
          fallback: '1.0.0'

      - name: Get version
        id: version
        uses: "WyriHaximus/github-action-next-semvers@v1"
        with:
          version: ${{ steps.tag.outputs.tag }}

      - name: Setup java-maven
        uses: quiz-me-up/reusable-workflow/.github/actions/setup-java-maven@master

      - name: Update pom.xml versions
        run: mvn versions:set -DnewVersion=${{ steps.version.outputs.major }} -DprocessAllModules=true -DgenerateBackupPoms=false

      - name: Commit and Tag
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --allow-empty -m "ci: bump version to ${{ steps.version.outputs.v_major }}"
          git tag ${{ steps.version.outputs.v_major }}
      
      - name: Push changes
        run: git push origin master --follow-tags
